//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.04.17 at 02:14:49 PM CEST 
//


package net.sourceforge.align.util.bind.al;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}sourcelist"/>
 *         &lt;element ref="{}targetlist"/>
 *       &lt;/all>
 *       &lt;attribute ref="{}score"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "alignment")
public class Alignment {

    @XmlElement(required = true)
    protected Segmentlist sourcelist;
    @XmlElement(required = true)
    protected Segmentlist targetlist;
    @XmlAttribute
    protected Double score;

    /**
     * Gets the value of the sourcelist property.
     * 
     * @return
     *     possible object is
     *     {@link Segmentlist }
     *     
     */
    public Segmentlist getSourcelist() {
        return sourcelist;
    }

    /**
     * Sets the value of the sourcelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Segmentlist }
     *     
     */
    public void setSourcelist(Segmentlist value) {
        this.sourcelist = value;
    }

    /**
     * Gets the value of the targetlist property.
     * 
     * @return
     *     possible object is
     *     {@link Segmentlist }
     *     
     */
    public Segmentlist getTargetlist() {
        return targetlist;
    }

    /**
     * Sets the value of the targetlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Segmentlist }
     *     
     */
    public void setTargetlist(Segmentlist value) {
        this.targetlist = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setScore(Double value) {
        this.score = value;
    }

}
