#!/bin/bash

SCRIPT_DIR=`dirname $0`
PROJECT_HOME=$SCRIPT_DIR/../..

$PROJECT_HOME/bin/maligna parse -c txt $PROJECT_HOME/example/txt/poznan-pl.txt $PROJECT_HOME/example/txt/poznan-de.txt  |  $PROJECT_HOME/bin/maligna modify -c split-sentence  |  $PROJECT_HOME/bin/maligna modify -c trim  >  poznan-split.al

cat poznan-split.al  |  $PROJECT_HOME/bin/maligna align -c fb -a poisson -n word -s iterative-band  |  $PROJECT_HOME/bin/maligna select -c one-to-one  |  $PROJECT_HOME/bin/maligna select -c fraction -f 0.85  >  poznan-align-length.al

cat poznan-split.al  |  $PROJECT_HOME/bin/maligna align -c fb -a poisson,translation -n word -s iterative-band -t poznan-align-length.al  >  poznan-align.al
